[tool.black]
line_length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | __pycache__
    | build
    | dist
    | docs
    | .tox
    | *.egg-info
    | venv
    | env
)/
'''
skip_string_normalization = true
ensure_newline_at_eof = true
# 使用 LF 换行符
line_ending = 'lf'
